import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Messages from '@/components/Messages/Messages';
import Message from '@/components/Message/Message';
import { ThemeContext } from "../../theme/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContext>
          <div className="container">
            <div className="wrapper">
              <Navbar />
              {children}
              <Messages/>
              <Message/>
            </div>
          </div>
        </ThemeContext>
      </body>
    </html>
  );
}
